### ISSUE TITLE
Failure to open RFCOMM channel when mRFCOMMChannel = nil

### ISSUE THREAD

**Issue by madiver** [garvincasimir/coco-bluetooth-rfcomm-swift#1]
@garvincasimir first of all, thanks so much for example of RFCOMM using SWIFT.  It's the _ONLY_ example in SWIFT I've found in days of searching.  One question I was hoping you could answer is when I attempt to run this application after compiling it with SWIFT 2.1,  it fails when attempting to open the RFCOMM channel complaining that mRFCOMMChannel is nil.  I've pulled my hair out trying to figure it out with no luck thus far.  Any tips would be much appreciated. 

device.openRFCOMMChannelAsync(mRFCOMMChannel, withChannelID: rfcommChannelID.memory, delegate: self)

**Comment by garvincasimir** [comment]
Hi @madiver I am happy to hear that you find the sample useful. This was a port from objective-c to an early version of swift so I am not surprised if it is broken right now. I will fire up xcode and attempt to figure out the problem.

**Comment by madiver** [comment]
Hi @garvincasimir, I think I stumbled onto the solution:

var mRFCOMMChannel: IOBluetoothRFCOMMChannel? = IOBluetoothRFCOMMChannel()

device.openRFCOMMChannelAsync(&mRFCOMMChannel, withChannelID: rfcommChannelID, delegate: self) != kIOReturnSuccess

The above doesn't fix everything but I think the rest is probably more straightforward to figure out now that I'm starting to better understand how swift handles pointers.

**Comment by garvincasimir** [comment]
I made some updates that seem to be working now. I am not completely happy about it because there is some unsafe stuff in there but it should be enough for you to move forward.

**Comment by madiver** [comment]
Thanks! A huge help! I'll pay it forward!

**Comment by garvincasimir** [comment]
No Problem!

On Sat, May 7, 2016 at 10:01 PM, Mark W. Bennett notifications@github.com
wrote:

> Thanks! A huge help! I'll pay it forward!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/garvincasimir/coco-bluetooth-rfcomm-swift/issues/1#issuecomment-217682876

## 

Genius is one percent inspiration and ninety-nine percent perspiration -
Thomas A. Edison
